export default function Head() {
  return (
    <>
      <title>Frontend Mentor | News homepage</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="shortcut icon" type="image/png" href="/favicon-32x32.png" />
    </>
  );
}
